
data_path: 'data/data_ChEMBL_BindingDB_sort.csv'
col_prots: 'Sequence'
col_mols: 'SMILES'
d_model: 1024
num_heads: 8
ff_hidden_layer: 4096
dropout: 0.1
num_layers: 4
batch_size: 10
num_epochs: 10
learning_rate: 0.0001
loss_function: 'crossentropy'
optimizer: 'Adam'
weights_path: 'weights/best_model_weights.pth'
teacher_forcing: False
validation_split: 0.2
get_wandb: False
wandb_project: 'train_decoder_parallel'
num_gpus: 2
verbose: True
