
data_path: 'data/data_seqmol_BindingDB_filt.csv'
col_prots: 'Sequence'
col_mols: 'SMILES'
protein_tokenizer: 'facebook/esm2_t33_650M_UR50'
smiles_tokenizer: 'ibm/MolFormer-XL-both-10pct'
d_model: 1000
num_heads: 8
ff_hidden_layer: 4000
dropout: 0.1
num_layers: 12
batch_size: 8
num_epochs: 10
learning_rate: 0.0001
loss_function: 'crossentropy'
optimizer: 'Adam'
weights_path: 'weights/best_model_weights.pth'
teacher_forcing: False
get_wandb: False
wandb_project: 'train_decoder_parallel'
num_gpus: 2
